frr defaults traditional
hostname core01
no ipv6 forwarding
!
interface lo
 ip address 10.255.0.1/32
 ip ospf area 0
!
interface eth1
 ip address 10.0.0.1/30
 ip ospf network point-to-point
 ip ospf area 0
!
interface eth2
 ip address 10.0.1.1/30
 ip ospf network point-to-point
 ip ospf area 0
!
interface eth9
 ip address 10.0.9.1/30
 ip ospf network point-to-point
 ip ospf area 0
!
router ospf
 ospf router-id 10.255.0.1
 redistribute connected
!
line vty
!
