frr defaults traditional
hostname spur-a3
no ipv6 forwarding
!
interface lo
 ip address 10.255.0.33/32
 ip ospf area 0
!
interface eth1
 ip address 10.0.7.2/30
 ip ospf network point-to-point
 ip ospf area 0
!
router ospf
 ospf router-id 10.255.0.33
 redistribute connected
!
line vty
!
