frr defaults traditional
hostname spur-a1
no ipv6 forwarding
!
interface lo
 ip address 10.255.0.31/32
 ip ospf area 0
!
interface eth1
 ip address 10.0.5.2/30
 ip ospf network point-to-point
 ip ospf area 0
!
interface eth2
 ip address 10.0.6.1/30
 ip ospf network point-to-point
 ip ospf area 0
!
router ospf
 ospf router-id 10.255.0.31
 redistribute connected
!
line vty
!
